name: flutter_pin_code_fields
description: A flutter package which will help you generate customizable pin code fields. Can be used for login pins or OTP.
version: 1.2.0
homepage: https://github.com/sanifhimani/flutter_pin_code_fields

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
dev_dependencies:
  lints: ^2.0.1
