name: flutter_pin_code_fields
description: A flutter package which will help you generate customizable pin code fields. Can be used for login pins or OTP.
version: 2.1.0
homepage: https://github.com/sanifhimani/flutter_pin_code_fields
repository: https://github.com/sanifhimani/flutter_pin_code_fields
issue_tracker: https://github.com/sanifhimani/flutter_pin_code_fields/issues

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  test:
